### PR TITLE
Update composer.json

### LINKED ISSUE #68: Fatal Compile Error: Declaration of Http\Client\Socket\Stream::close() must be compatible
```
Fatal Compile Error: Declaration of Http\Client\Socket\Stream::close()
must be compatible with Psr\Http\Message\StreamInterface::close(): void
```

```
$ composer show php-http/socket-client | grep version
versions : * 2.1.1
$ composer show psr/http-message | grep version
versions : * 2.0
```

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #68

### CODE REVIEW

**Comment by ro0NL** [comment]
cc @dbu

**Comment by dbu** [comment]
some code rot (or rather testing rot) going in this repository. the latest tests fail but it seems to me it is because of some setup issue, not because of your change.

i was [proposing](https://github.com/php-http/documentation/pull/310#discussion_r1193398598) to abandon the socket client as it is not actively maintained and should be upgraded to the PSR standards instead of php-http.

if you want to look into why the php tests fail, please do but unless a new maintainer steps up, i plan to abandon this client soonish.

**Comment by ro0NL** [comment]
it's currently part of crucial printer infrastructure on our side; https://github.com/etrias-nl/cups-ipp/blob/master/src/Transport/Client.php

i figured we are best of by embedding the socket client directly :+1:

**Comment by ro0NL** [comment]
for future reference, it's about `psr/http-message` NOT `php-http/message` :facepalm:

**Comment by dbu** [comment]
@ro0NL if you want, i can also give you commit rights on the php-http/socket-client if you want to keep maintaining it.

it is really more of a resource question that i want to abandon it, not that i think it should not exist.

**Comment by ro0NL** [comment]
sorry :) i believe everything should live under symfony/http-client umbrella :sweat_smile: 

im not sure it's currently possible with Symfony's `NativeHttpClient`, but perhaps that's the better migration path for this repository

otherwise just abandon it, the decision should be made tho ;)

**Comment by dbu** [comment]
this repository does not have a direct relation to symfony http clients... but if that is a good migration path for you, go for it. when we actually mark the repository as abandoned, you will have panicked users though, i am afraid :-/ (even though there is no need to panik, its not like we delete the repository in the next couple of years, only mark as abandoned...)

**Pull request closed without merging**
