### PR TITLE
Support SF6

### LINKED ISSUE #60: Not installable with a Symfony 6 project
**PHP version**: 8.0+

**Description**
This library requires symfony/options-resolver on version 5.* or below, but Symfony 6.0 has been released 1 month ago.

**How to reproduce**
Use this library with a project build on Symfony 6.0

**Possible Solution**
Update composer.json to support also `symfony/options-resolver` with the version 6.0

### PR DESCRIPTION
**Pull request by frenchcomp**
| Q               | A
| --------------- | ---
| Bug fix?         | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #60
| Documentation   | n/a
| License         | MIT

#### What's in this PR?

Update the composer.json file to use this library with project build on Symfony 6.0

#### Why?

This library requires `symfony/options-resolver` from 2.6 to 5.4

#### Checklist

- [x ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by frenchcomp** [comment]
Hi,
Is this project still maintained? Your CI seems broken.
Thanks
Richard

**Comment by wmouwen** [comment]
Hi there.

We are wondering the same as @frenchcomp . The issue this PR resolves is slowly becoming a blocking issue.

Thanks.

**Comment by andrew-demb** [comment]
@joelwurtz @sagikazarmark @Nyholm @xabbuh 
Hi. Could you help with proceeding with this PR, please?

**Comment by wmouwen** [comment]
Reminder for @joelwurtz and @Nyholm . This issue has become blocking for us. Could you help us with proceeding this PR?

**Review by Nyholm — APPROVED** [review]
The option resolver has not changed since 2.0. This is save to merge. 

Im hesitant to release this before we have proper CI again. See #63

**Pull request merged**
